{
 "title": "ML App",
 "time": { "from": "2024-09-18T18:23:12.367Z", "to": "2024-09-18T19:26:41.354Z" },
 "panels": [
  {
   "title": "Actual physical memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "CPU TIme",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Reques Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_bucket[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC objects collected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Reques Duration Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "cos(flask_http_request_duration_seconds_created)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}