{
 "title": "Node Exporter",
 "time": { "from": "2024-09-18T10:19:50.626Z", "to": "2024-09-18T22:19:50.626Z" },
 "panels": [
  {
   "title": "Average system load over the last 1 minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Total number of bytes allocated in memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time spend by Go runtime in gc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Average system load over the last 15 minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "node_load15", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Average system load over the last 5 minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "node_load5", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total memory in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "node_memory_Active_anon_bytes", "legendFormat": "{{job}}" }
   ]
  }
 ]
}