# Global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "app"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ml_app"
    static_configs:
      - targets: ["localhost:80"]

  - job_name: "mlflow_metrics"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:5000"]
