channels:
- conda-forge
dependencies:
- python=3.9.18
- pip<=24.2
- pip:
  - mlflow==2.15.1
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - psutil==6.0.0
  - scikit-learn==1.2.2
  - scipy==1.13.1
name: mlflow-env
